version: '3.7'

services:
  app:
    container_name: ${PROJECT_NAME}-app
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - IMAGE_VERSION=2.0.0-npm
    image: ${PROJECT_NAME}/php
    working_dir: /var/www/html
    restart: unless-stopped
    tty: true
    env_file:
      - ./.env
    ports:
      - ${APP_PORT_HTTP}:80
      - ${APP_PORT_HTTPS}:443
    volumes:
      - ./www/:/var/www/html
    networks:
      - network-backend
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: ${PROJECT_NAME}-db
    image: mysql:8.0.27
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    ports:
      - ${DB_PORT}:3306
    networks:
      - network-backend
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u ${MYSQL_USER} --password=${MYSQL_PASSWORD}"
      interval: 5s
      retries: 50
      start_period: 2m30s

networks:
  network-backend:
    driver: bridge
